Web/TheBedstand.Web/Controllers/GenresController.cs
namespace TheBedstand.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using TheBedstand.Common;
    using TheBedstand.Services;
    using TheBedstand.Services.Data;
    using TheBedstand.Web.InputModels.Genres;

    public class GenresController : BaseController
    {
        private readonly IGenresService genresService;
        private readonly ICloudinaryService cloudinaryService;

        public GenresController(IGenresService genresService, ICloudinaryService cloudinaryService)
        {
            this.genresService = genresService;
            this.cloudinaryService = cloudinaryService;
        }

        [Authorize]
        [HttpGet]
        public IActionResult All()
        {
            var viewModel = this.genresService.GetAll();

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpGet]
        public IActionResult Create()
        {
            var model = new CreateGenreInputModel();

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> Create(CreateGenreInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var result = await this.cloudinaryService.UploadPhotoAsync(input.Image, $"{input.Name}", GlobalConstants.CloudFolderForGenrePhotos);

            await this.genresService.CreateAsync(input.Name, input.Description, result?.Uri.AbsoluteUri);

            return this.RedirectToAction(nameof(this.All));
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var genre = this.genresService.GetbyId(id);
            var model = new CreateGenreInputModel { Description = genre.Description, Name = genre.Name };

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> Edit(CreateGenreInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var genre = this.genresService.GetbyId(input.Id);

            if (input.Image != null)
            {
                var uploadResult = await this.cloudinaryService.UploadPhotoAsync(input.Image, $"{input.Name}", GlobalConstants.CloudFolderForGenrePhotos);

                if (uploadResult != null && uploadResult.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    await this.cloudinaryService.Delete(genre.ImageId);

                    genre.ImageId = uploadResult.PublicId;
                    genre.ImageUrl = uploadResult.Uri.AbsoluteUri;
                }
                else
                {
                    this.TempData["ImageUploadError"] = "Failed to upload image.";
                    return this.View(input);
                }
            }

            genre.Name = input.Name;
            genre.Description = input.Description;

            await this.genresService.PersistChanges();

            return this.RedirectToAction("All");
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await this.genresService.Delete(id);

            if (result)
            {
                this.TempData["result"] = "Successfuly deleted the genre.";
                return this.RedirectToAction("All");
            }
            else
            {
                this.TempData["result"] = "Failed to delete the genre.";
                return this.RedirectToAction("All");
            }
        }
    }
}

Web/TheBedstand.Web/Views/Genres/All.cshtml
@model TheBedstand.Web.ViewModels.Genres.AllGenresViewModel
@using TheBedstand.Common
@{
    ViewData["Title"] = "All";
}

@if (TempData["result"] != null)
{
    @if (TempData["result"].ToString() == "Successfuly deleted the genre.")
    {
        <div class="alert alert-success my-2" role="alert">
            @TempData["result"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    else if (TempData["result"].ToString() == "Failed to delete the genre.")
    {
        <div class="alert alert-warning my-2" role="alert">
            @TempData["result"].ToString()
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

<div class="row">
    @foreach (var genre in Model.Genres)
    {
        <div class="col-md-3  py-2 px-2 d-flex align-items-stretch">
            <div class="card">
                <img class="card-img d-flex" src="@genre.ImageUrl" width="200" height="200" alt="Genre Image">
                <div class="card-body bg-light">
                    <h5 class="card-title">@genre.Name</h5>
                    <p>@genre.Description</p>
                </div>
                <div class="card-footer">
                    <a class="btn btn-light" href="/Books/GetByGenre?id=@genre.Id" role="button">See More</a>
                    @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                    {
                        <div class="row mt-1">
                            <a class="btn btn-warning btn-sm col-6" href="/Genres/Edit?id=@genre.Id">Edit</a>
                            <a class="btn btn-danger btn-sm col-6 " href="/Genres/Delete?id=@genre.Id">Delete</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
</div>

Web/TheBedstand.Web/Views/Genres/Create.cshtml
@model TheBedstand.Web.InputModels.Genres.CreateGenreInputModel
@{
    ViewData["Title"] = "Create";
}

<form asp-controller="Genres" asp-action="Create" class="px-2 py-2 bg-gray mx-auto" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="Name" class="text-dark">Genre Name</label>
        <input asp-for="Name" class="form-control w-25" type="text" id="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="Description" class="text-dark">Description</label>
        <textarea asp-for="Description" class="form-control" type="text" placeholder="Enter the genres description here..." id="Description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Image" class="upload-btn">
            <i class="fa fa-upload"></i> Upload
            <input asp-for="Image" type="file" />
        </label>
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>

    <button class="btn-primary btn" type="submit">Create</button>
</form>

Web/TheBedstand.Web/Views/Genres/Edit.cshtml
@model TheBedstand.Web.InputModels.Genres.CreateGenreInputModel

@if (this.TempData["ImageUploadError"] != null)
{
    <div class="alert alert-warning my-2" role="alert">
        @this.TempData["ImageUploadError"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
    

<form asp-controller="Genres" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="Name" class="text-dark">Genre Name</label>
        <input asp-for="Name" class="form-control w-25" type="text" id="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="Description" class="text-dark">Description</label>
        <textarea asp-for="Description" class="form-control" type="text" placeholder="Enter the genres description here..." id="Description"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Image" class="upload-btn">
            <i class="fa fa-upload"></i> Upload
            <input asp-for="Image" type="file" />
        </label>
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>

    <div> <input asp-for="Id" type="number" style="display:none"/></div>

    <button class="btn-primary btn" type="submit">Edit</button>
</form>