Web/TheBedstand.Web/Areas/Administration/Controllers/AdministratorsController.cs
namespace TheBedstand.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using TheBedstand.Common;
    using TheBedstand.Data.Models;
    using TheBedstand.Web.Filters;
    using TheBedstand.Web.InputModels.Administrators;
    using TheBedstand.Web.ViewModels.Administrators;

    [ServiceFilter(typeof(AuthorizeRootUserAttribute))]
    [Area("Administration")]
    public class AdministratorsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public AdministratorsController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var users = await this.userManager.GetUsersInRoleAsync(GlobalConstants.AdministratorRoleName);

            var model = users.Where(x => x.UserName != "root_user").Select(x => new AdminListViewModel { Id = x.Id, Username = x.UserName });

            return this.View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AdministratorInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var admin = new ApplicationUser { UserName = input.Username, Email = input.Email, };
            var result = await this.userManager.CreateAsync(admin, input.Password);

            if (result.Succeeded)
            {
                await this.userManager.AddToRoleAsync(admin, GlobalConstants.AdministratorRoleName);

                return this.RedirectToAction("All");
            }
            else
            {
                return this.View(input);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await this.userManager.FindByIdAsync(id);

            var userRoles = await this.userManager.GetRolesAsync(user);

            foreach (var role in userRoles)
            {
                await this.userManager.RemoveFromRoleAsync(user, role.ToString());
            }

            var result = await this.userManager.DeleteAsync(user);

            if (result.Succeeded)
            {
                this.TempData["result"] = "Success!";
                return this.RedirectToAction("All");
            }
            else
            {
                this.TempData["result"] = "Failure!";
                return this.RedirectToAction("All");
            }
        }
    }
}

Web/TheBedstand.Web/Controllers/AdministratorsController.cs
namespace TheBedstand.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using TheBedstand.Common;
    using TheBedstand.Data.Models;
    using TheBedstand.Web.InputModels.Administrators;
    using TheBedstand.Web.ViewModels.Administrators;

    public class AdministratorsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public AdministratorsController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> All()
        {
            var users = await this.userManager.GetUsersInRoleAsync(GlobalConstants.AdministratorRoleName);

            var model = users.Where(x => x.UserName != "root_user").Select(x => new AdminListViewModel { Id = x.Id, Username = x.UserName });

            return this.View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AdministratorInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            var admin = new ApplicationUser { UserName = input.Username, Email = input.Email, };
            var result = await this.userManager.CreateAsync(admin, input.Password);

            if (result.Succeeded)
            {
                await this.userManager.AddToRoleAsync(admin, GlobalConstants.AdministratorRoleName);

                return this.RedirectToAction("All");
            }
            else
            {
                return this.View(input);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await this.userManager.FindByIdAsync(id);

            var userRoles = await this.userManager.GetRolesAsync(user);

            foreach (var role in userRoles)
            {
                await this.userManager.RemoveFromRoleAsync(user, role.ToString());
            }

            var result = await this.userManager.DeleteAsync(user);

            if (result.Succeeded)
            {
                this.TempData["result"] = "Success!";
                return this.RedirectToAction("All");
            }
            else
            {
                this.TempData["result"] = "Failure!";
                return this.RedirectToAction("All");
            }
        }
    }
}

Web/TheBedstand.Web/Areas/Administration/Views/Administrators/Add.cshtml
@model TheBedstand.Web.InputModels.Administrators.AdministratorInputModel
@{
    ViewData["Title"] = "Add";
}

<div class="px-2 py-2 bg-gray w-50 mx-auto">
    <form asp-controller="Administrators" asp-action="Add" method="post">
        <h4>Create a new administrator account.</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Username"></label>
            <input asp-for="Username" class="form-control w-50" />
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <input asp-for="Email" class="form-control w-50" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Password"></label>
            <input asp-for="Password" class="form-control w-50" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ConfirmPassword"></label>
            <input asp-for="ConfirmPassword" class="form-control w-50" />
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>

Web/TheBedstand.Web/Areas/Administration/Views/Administrators/All.cshtml
@model IEnumerable<TheBedstand.Web.ViewModels.Administrators.AdminListViewModel>
@using TheBedstand.Common;

@if (TempData["result"] != null)
{
    if (TempData["result"].ToString() == "Success!")
    {
        <div class="alert alert-success my-2" role="alert">
            Admin successfully deleted.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    else
    {
        <div class="alert alert-warning my-2" role="alert">
            Admin was not deleted.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
}

<div>
    @foreach (var admin in Model)
    {
        <div class="row py-1 my-1 border border-dark bg-gray">
            <p class="col-6 text-center font-weight-bold my-auto">
                @admin.Username
            </p>
            <a class="btn btn-danger col-2" href="/Administrators/Delete?id=@admin.Id">DELETE</a>
        </div>
    }

</div>