Web/TheBedstand.Web/Controllers/AuthorsController.cs
namespace TheBedstand.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using TheBedstand.Common;
    using TheBedstand.Common.Helpers;
    using TheBedstand.Data.Models.Enums;
    using TheBedstand.Services;
    using TheBedstand.Services.Data;
    using TheBedstand.Web.InputModels.Authors;
    using TheBedstand.Web.ViewModels.Authors;
    using TheBedstand.Web.ViewModels.Books;

    public class AuthorsController : Controller
    {
        private readonly IAuthorsService authorsService;
        private readonly ICloudinaryService cloudinaryService;

        public AuthorsController(IAuthorsService authorsService, ICloudinaryService cloudinaryService)
        {
            this.authorsService = authorsService;
            this.cloudinaryService = cloudinaryService;
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpGet]
        public IActionResult Create()
        {
            var model = new AuthorInputModel();
            this.AttachAuthorsForSelectListToInputModel(model);

            return this.View(model);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> Create(AuthorInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                this.AttachAuthorsForSelectListToInputModel(input);
                return this.View(input);
            }

            if (input.Image != null)
            {
                var result = await this.cloudinaryService
                .UploadPhotoAsync(input.Image, $"{input.PersonalName + " " + input.Surname}", GlobalConstants.CloudFolderForAuthorsPhotos);

                await this.authorsService.CreateAsync(input, result);
            }

            return this.RedirectToAction("Index", "Home");
        }

        [Authorize]
        [HttpGet]
        public IActionResult All()
        {
            var model = this.authorsService.GetAuthorBasicInfo();
            return this.View(model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Details(int id)
        {
            var author = this.authorsService.GetById(id);

            var viewModel = new AuthorDetailsViewModel
            {
                Biography = author.Biography,
                Country = EnumDescriptionHelper.GetEnumValueDescription<Country>(author.Country),
                DateOfBirth = author.DateOfBirth,
                ImageUrl = author.ImageUrl,
                Surname = author.Surname,
                PersonalName = author.PersonalName,
                Id = author.Id,
                PseudonymForAuthor = author.PseudonymFor == null ? "N/A" : NameHelper.GetFullName(author.PseudonymFor.PersonalName, author.PseudonymFor.Surname),
                Genres = author.Books.SelectMany(b => b.BookGenres).Select(bg => bg.Genre?.Name).Distinct().ToArray(),
                Books = author.Books.Select(b => new BookAuthorPageViewModel
                {
                    Id = b.Id,
                    Title = b.Title,
                    CoverUrl = b.CoverUrl,
                }).ToList(),
            };

            return this.View(viewModel);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var author = this.authorsService.GetById(id);

            var authorInputModel = new AuthorInputModel
            {
                Id = id,
                Biography = author.Biography,
                Country = author.Country,
                DateOfBirth = author.DateOfBirth,
                PersonalName = author.PersonalName,
                Surname = author.Surname,
                PseudonymForId = author.PseudonymForId,
            };

            var authorWithAttachedSelectList = this.AttachAuthorsForSelectListToInputModel(authorInputModel);

            return this.View(authorWithAttachedSelectList);
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpPost]
        public async Task<IActionResult> Edit(AuthorInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(this.AttachAuthorsForSelectListToInputModel(input));
            }

            var author = this.authorsService.GetById(input.Id);

            if (input.Image != null)
            {
                await this.cloudinaryService.Delete(author.ImageUrl);

                var result = await this.cloudinaryService
                .UploadPhotoAsync(input.Image, $"{input.PersonalName + " " + input.Surname}", GlobalConstants.CloudFolderForAuthorsPhotos);

                author.ImageUrl = result?.Uri?.AbsoluteUri;
                author.ImageId = result?.PublicId;
            }

            author.Biography = input.Biography;
            author.Country = input.Country;
            author.DateOfBirth = input.DateOfBirth;
            author.PersonalName = input.PersonalName;
            author.Surname = input.Surname;
            author.PseudonymForId = input.PseudonymForId != null ? (int?)this.authorsService.GetById((int)input.PseudonymForId).Id : null;

            await this.authorsService.PersistEditedAuthorToDb();

            return this.RedirectToAction("Details", new { id = author.Id });
        }

        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await this.authorsService.Delete(id);

            return this.RedirectToAction("All");
        }

        private AuthorInputModel AttachAuthorsForSelectListToInputModel(AuthorInputModel input)
        {
            input.AuthorsForSelectList = this.authorsService.GetAuthorBasicInfo();

            return input;
        }
    }
}

Web/TheBedstand.Web/Views/Authors/All.cshtml
@model IEnumerable<TheBedstand.Web.ViewModels.Authors.AuthorBasicInfoModel>;

<nav class="my-3" aria-label="Authors navigation">
    <ul class="pagination justify-content-center">
        <li id="PageA" class="page-item disabled"><a class="page-link" onclick="togglePageItems('A');" href="javascript:void(0);">A</a></li>
        <li id="PageB" class="page-item"><a class="page-link" onclick="togglePageItems('B');" href="javascript:void(0);">B</a></li>
        <li id="PageC" class="page-item"><a class="page-link" onclick="togglePageItems('C');" href="javascript:void(0);">C</a></li>
        <li id="PageD" class="page-item"><a class="page-link" onclick="togglePageItems('D');" href="javascript:void(0);">D</a></li>
        <li id="PageE" class="page-item"><a class="page-link" onclick="togglePageItems('E');" href="javascript:void(0);">E</a></li>
        <li id="PageF" class="page-item"><a class="page-link" onclick="togglePageItems('F');" href="javascript:void(0);">F</a></li>
        <li id="PageG" class="page-item"><a class="page-link" onclick="togglePageItems('G');" href="javascript:void(0);">G</a></li>
        <li id="PageH" class="page-item"><a class="page-link" onclick="togglePageItems('H');" href="javascript:void(0);">H</a></li>
        <li id="PageI" class="page-item"><a class="page-link" onclick="togglePageItems('I');" href="javascript:void(0);">I</a></li>
        <li id="PageJ" class="page-item"><a class="page-link" onclick="togglePageItems('J');" href="javascript:void(0);">J</a></li>
        <li id="PageK" class="page-item"><a class="page-link" onclick="togglePageItems('K');" href="javascript:void(0);">K</a></li>
        <li id="PageL" class="page-item"><a class="page-link" onclick="togglePageItems('L');" href="javascript:void(0);">L</a></li>
        <li id="PageM" class="page-item"><a class="page-link" onclick="togglePageItems('M');" href="javascript:void(0);">M</a></li>
        <li id="PageN" class="page-item"><a class="page-link" onclick="togglePageItems('N');" href="javascript:void(0);">N</a></li>
        <li id="PageO" class="page-item"><a class="page-link" onclick="togglePageItems('O');" href="javascript:void(0);">O</a></li>
        <li id="PageP" class="page-item"><a class="page-link" onclick="togglePageItems('P');" href="javascript:void(0);">P</a></li>
        <li id="PageQ" class="page-item"><a class="page-link" onclick="togglePageItems('Q');" href="javascript:void(0);">Q</a></li>
        <li id="PageR" class="page-item"><a class="page-link" onclick="togglePageItems('R');" href="javascript:void(0);">R</a></li>
        <li id="PageS" class="page-item"><a class="page-link" onclick="togglePageItems('S');" href="javascript:void(0);">S</a></li>
        <li id="PageT" class="page-item"><a class="page-link" onclick="togglePageItems('T');" href="javascript:void(0);">T</a></li>
        <li id="PageU" class="page-item"><a class="page-link" onclick="togglePageItems('U');" href="javascript:void(0);">U</a></li>
        <li id="PageV" class="page-item"><a class="page-link" onclick="togglePageItems('V');" href="javascript:void(0);">V</a></li>
        <li id="PageW" class="page-item"><a class="page-link" onclick="togglePageItems('W');" href="javascript:void(0);">W</a></li>
        <li id="PageX" class="page-item"><a class="page-link" onclick="togglePageItems('X');" href="javascript:void(0);">X</a></li>
        <li id="PageY" class="page-item"><a class="page-link" onclick="togglePageItems('Y');" href="javascript:void(0);">Y</a></li>
        <li id="PageZ" class="page-item"><a class="page-link" onclick="togglePageItems('Z');" href="javascript:void(0);">Z</a></li>
    </ul>
</nav>

@for (int i = 'A'; i <= 'Z'; i++)
{
    <div id="@("AuthorsWith"+(char)i)" class="row my-3 justify-content-center text-center" style="@(i=='A' ? "" : "display: none")">
        @foreach (var author in Model.Where(x => x.Surname.StartsWith((char)i)).OrderBy(x => x.Surname))
        {
            <div class="bg-light col-3 my-2 mx-1" style="font-size: 20px">
                <a href="/Authors/Details?id=@author.Id" class="text-dark"><strong>@author.Surname</strong>, <text>@author.PersonalName</text></a>
            </div>
        }
    </div>
}

<script type="text/javascript">
    function togglePageItems(letter) {

        let divId = "AuthorsWith" + letter;
        let pageId = "Page" + letter;

        $('div[id^="AuthorsWith"]').hide();
        $("#" + divId).show();

        $('.page-item').removeClass('disabled');
        $("#" + pageId).addClass('disabled');
    }
</script>

Web/TheBedstand.Web/Views/Authors/Create.cshtml
@model TheBedstand.Web.InputModels.Authors.AuthorInputModel;
@using TheBedstand.Data.Models.Enums;
@using TheBedstand.Common.Helpers;

    <form class="container bg-light mt-3" asp-controller="Authors" asp-action="Create" method="post" enctype="multipart/form-data">

        <div class="form-group">
            <label class="text-dark" for="PersonalName">Personal Name</label>
            <input asp-for="PersonalName" class="form-control w-25" type="text" id="PersonalName" />
            <span asp-validation-for="PersonalName"></span>
        </div>

        <div class="form-group">
            <label class="text-dark" for="PersonalName">Surname</label>
            <input asp-for="Surname" class="form-control w-25" type="text" id="Surname" />
            <span asp-validation-for="Surname" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label class="text-dark" for="Biography">Biography</label>
            <textarea asp-for="Biography" class="form-control w-50" type="text" placeholder="Enter the author's biography here..." id="Biography"></textarea>
            <span asp-validation-for="Biography" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label class="text-dark" for="Biography">Date of Birth</label>
            <input asp-for="DateOfBirth" class="form-control w-50" type="date" id="DateOfBirth">
            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label class="text-dark" for="C">Pseudonym For</label>
            <select asp-for="PseudonymForId" asp-items="@(Model.AuthorsForSelectList.Select(a => new SelectListItem { Text = NameHelper.GetFullName(a.PersonalName, a.Surname), Value = a.Id.ToString() })); ">
                <option selected="selected" value="">Please select</option>
            </select>
            <span asp-validation-for="PseudonymForId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label class="text-dark" for="C">Country</label>
            <select asp-for="Country" asp-items="@CountryForSelectList<Country>.GetValuesForSelectList().Select(a => new SelectListItem { Text = a.Text, Value = a.Value.ToString()})">
                <option selected="selected" value="">Please select</option>
            </select>
            <span asp-validation-for="Country" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Image" class="upload-btn">
                <i class="fa fa-upload"></i> Upload
                <input asp-for="Image" type="file" />
            </label>
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>

        <button class="btn-primary btn my-2" type="submit">Create</button>
    </form>

Web/TheBedstand.Web/Views/Authors/Details.cshtml
@model TheBedstand.Web.ViewModels.Authors.AuthorDetailsViewModel
@using TheBedstand.Common.Helpers
@using TheBedstand.Common

<div class="bg-gray my-2 pb-2">
    <div class="row">
        <div class="col-3 py-2 mx-2">
            <img src="@Model.ImageUrl" class="w-100" />
        </div>
        <div class="col-7">
            <h3>@NameHelper.GetFullName(Model.PersonalName, Model.Surname)</h3>

            @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                <div class="d-inline-block">
                    <a class="btn btn-warning" href="/Authors/Edit?id=@Model.Id">Edit</a>
                    <a class="btn btn-danger" href="/Authors/Delete?id=@Model.Id">Delete</a>
                </div>
            }

            <hr />
            <div class="row">
                <span class="font-weight-bold col-3">Born:</span>
                <span class="col-9">@Model.DateOfBirth.Value.ToString("dd/MM/yyyy")</span>
            </div>
            <div class="row">
                <span class="font-weight-bold col-3">Country:</span>
                <span class="col-9">@(Model.Country)</span>
            </div>
            <div class="row">
                <span class="font-weight-bold col-3">Pseudonym for:</span>
                <span class="col-9">@Model.PseudonymForAuthor</span>
            </div>
            <div class="row">
                <span class="font-weight-bold col-3">Genres:</span>
                <span class="col-9">@string.Join(", ", Model.Genres)</span>
            </div>
        </div>
    </div>

    <hr />
    <div class="mx-2 pb-1">
        <h6 class="text-center">Biography</h6>
        <p>
            @Model.Biography
        </p>
    </div>
    <hr />
    <h3 class="text-center">Books</h3>
    <hr />

    @foreach (var book in Model.Books)
    {
        <a href="/Books/Details?id=@book.Id" class="ml-4 my-2 row">
            <img width="100" src="@book.CoverUrl" />
            <h5 class="mx-auto my-auto">@book.Title</h5>
        </a>
    }
</div>

Web/TheBedstand.Web/Views/Authors/Edit.cshtml
@model TheBedstand.Web.InputModels.Authors.AuthorInputModel
@using TheBedstand.Common.Helpers
@using TheBedstand.Data.Models.Enums

@if (this.TempData["ImageUploadError"] != null)
{
    <div class="alert alert-warning my-2" role="alert">
        @this.TempData["ImageUploadError"]
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<form class="container bg-light mt-3" asp-controller="Authors" asp-action="Edit" method="post" enctype="multipart/form-data">

    <div class="form-group" style="display:none">
        <input asp-for="Id" class="form-control w-25" type="text" id="Id" />
    </div>

    <div class="form-group">
        <label class="text-dark" for="PersonalName">Personal Name</label>
        <input asp-for="PersonalName" class="form-control w-25" type="text" id="PersonalName" />
        <span asp-validation-for="PersonalName"></span>
    </div>

    <div class="form-group">
        <label class="text-dark" for="PersonalName">Surname</label>
        <input asp-for="Surname" class="form-control w-25" type="text" id="Surname" />
        <span asp-validation-for="Surname" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="text-dark" for="Biography">Biography</label>
        <textarea asp-for="Biography" class="form-control w-50" type="text" placeholder="Enter the author's biography here..." id="Biography"></textarea>
        <span asp-validation-for="Biography" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="text-dark" for="Biography">Date of Birth</label>
        <input asp-for="DateOfBirth" class="form-control w-50" type="date" id="DateOfBirth">
        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="text-dark" for="C">Pseudonym For</label>
        <select asp-for="PseudonymForId" asp-items="@(Model.AuthorsForSelectList.Select(a => new SelectListItem { Text = NameHelper.GetFullName(a.PersonalName, a.Surname), Value = a.Id.ToString() })); ">
            <option selected="selected" value="">Please select</option>
        </select>
        <span asp-validation-for="PseudonymForId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label class="text-dark" for="C">Country</label>
        <select asp-for="Country" asp-items="Html.GetEnumSelectList<Country>()">
            <option selected="selected" value="">Please select</option>
        </select>
        <span asp-validation-for="Country" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Image" class="upload-btn">
            <i class="fa fa-upload"></i> Upload
            <input asp-for="Image" type="file" />
        </label>
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>

    <button class="btn-primary btn my-2" type="submit">Edit</button>
</form>